# Welcome to Rokel Delivery Services!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Rokel Delivery Services (RDS)
email: moses.bangura@anu.edu.au
description: > # Rokel Delivery Services (RDS) coming soon...
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
#twitter_username: rds
#github_username:  dnovichman
name: Rokel Delivery Services

# Build settings
markdown: kramdown #redcarpet

#![Quadrotor Prototype](../images/DSC_0012.JPG){:class="img-responsive"}

